-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnyswKryihrbyMB64
cKj5xMwPtEFn5JDFUraEUrduhjCgCgYIKoZIzj0DAQehRANCAAShy/c+mox8xtpv
WkcHdjqj0AfbjOgzE8KBKp6rtbjH8Y/0F8gi9I/G+A8SS13Iz0ipc++ZSP3t0kHg
qGABvc9f
-----END PRIVATE KEY-----